### ISSUE TITLE
SI < 1.2 in peppol-validation-engine v3.1.0

### ISSUE THREAD

**Issue by humbeecc** [phax/peppol-validation-engine#2]
SimplerInvoicing 1.2 is supported since peppol-validation-engine v3.1.0. 

It seems that 1.1 is not supported anymore. Version 1.1 cannot be chosen anymore on the BIS2 Document Validation page and in the SimplerInvoicingValidation class, the 1.1 "public static final VESID" constants are gone...

It would be nice if older versions of SI remain supported.

Br, Chris.

**Comment by phax** [comment]
The problem was fixed in 3.1.1 release
